version: '3'

services:
  viz_app:
    container_name: viz_app
    image: viz_app:latest
    restart: always
    build: .
    expose:
      - "5000"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx_prod
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - viz_app