version: '3'

services:
  viz_app:
    container_name: viz_app
    image: viz_app:latest
    restart: always
    build: .
    expose:
      - "5000"

  nginx:
    container_name: nginx
    # restart: never
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - viz_app